emm_user:
    resource: "@EMMUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

emm_curso:
    resource: "@CursoMainBundle/Resources/config/routing.yml"
    prefix:   /