Curso\MainBundle\Entity\Producto:
    properties:
        nombre:
            - NotBlank: ~
            - Length:
                min: 3

            - Choice: { choices:[Camisa, Zapatos], message: Selecciona un producto valido.}

        precio:
            - NotBlank: ~
